### PR TITLE
[JS] fix: Fixed broken links related to auth samples in JS directory in SAMPLES.MD

### PR DESCRIPTION
**Pull request by gauravkeshre**
## Details

There were some links Inder JS directory that were not pointing to the files per their latest directory structure.

### CODE REVIEW

**Comment by Benjiiim** [comment]
Duplicate of #1990

**Review by corinagum — APPROVED** [review]
Thank you for the fixes! Super appreciate it. :)

**Comment by corinagum** [comment]
@gauravkeshre I do see that @Benjiiim filed a PR earlier, so I'm going to merge that in, but truly thank you for the contribution :)

**Comment by gauravkeshre** [comment]
Thank you @corinagum 
Please refer to the attached file for other broken links posted in this [issue 2000](https://github.com/microsoft/teams-ai/issues/2000)

**Pull request closed without merging**
