### PR TITLE
[PY] fixed feedback look dict accessed as object

### PR DESCRIPTION
**Pull request by yikwen**
Related to pull request #1892, not sure if @skoryky has seen the comment on the issue with reply_to_id. I've made similar changes.

### CODE REVIEW

**Comment by lilyydu** [comment]
Hi @yikwen,

since these changes are very similiar to #1892, could you suggest these fixes in that PR instead

**Comment by yikwen** [comment]
@lilyydu ok I've suggested changes in #1829. Hope I've done it correctly.

**Comment by lilyydu** [comment]
Hi @yikwen 

I received an email notif about the suggestion but don't see it on the #1892 PR for some reason- are you able to see it on your end?

**Comment by yikwen** [comment]
> Hi @yikwen
> 
> I received an email notif about the suggestion but don't see it on the #1892 PR for some reason- are you able to see it on your end?

@lilyydu yeah I can see it on #1892 

image

**Comment by skoryky** [comment]
> > Hi @yikwen
> > I received an email notif about the suggestion but don't see it on the #1892 PR for some reason- are you able to see it on your end?
> 
> @lilyydu yeah I can see it on #1892
> 
> image

I don't see it on the PR either, but acknowledging I see it here 😄 Working on it now.

**Comment by skoryky** [comment]
Hmm, I've been seeing the keys as camel-cased, i.e. `replyToId` and `actionName`. @yikwen, have you seen them be snake-cased, i.e. `reply_to_id` and `action_name`? @lilyydu, do you know what is expected?

**Comment by lilyydu** [comment]
@yikwen I see the 'Pending' - think you need to hit "Submit review" (going to close this PR now so we can discuss in #1892)

@skoryky Keys accesses should be snake cased - where did you see the camel-cases? we might have some discrepancies when we initially porting over code to python that need to be fixed

**Comment by skoryky** [comment]
@lilyydu, I saw that the request messages being sent from the the Bot Framework were camel-cased. Are you expecting some code in the Python library to convert that to snake case when loading into `context.activity`?

**Pull request closed without merging**
