### PR TITLE
Fixing all samples to make them Teams Toolkit v5 working correctly 

### PR DESCRIPTION
**Pull request by davrous**
Teams Toolkit v5 updates + fixing a small readme typo

PR to fix this issue: https://github.com/microsoft/teams-ai/issues/225

### CODE REVIEW

**Comment by therealjohn** [comment]
I will investigate the original problem in #225 too. When we updated these samples, I intentionally left `yarn install` out but can't recall why right now.

I also intentionally removed the `env-cmd` usage and provided defaults that would use `dotenv` instead.

**Comment by corinagum** [comment]
Hi @davrous thanks for the PR! Right now we're in a bit of a PR backlog for the js code, and I'd like to merge things in order. I'll be sure to get to yours as the preceding ones get checked in :)

**Review by corinagum — APPROVED** [review]
Belated realization, but I think the merge conflicts with the OpenAI Moderation PR will be minimal, so I'm going to merge this in. Thanks again David :)

**Comment by corinagum** [comment]
@therealjohn could you also leave a review as a fellow TTK expert? I'm assuming it's okay to keep `yarn`.

Some DevOps pipelines don't support yarn, however, so that might be one of your reasons?

**Review by therealjohn — CHANGES_REQUESTED** [review]
Should be no need for `env-cmd` since `dotenv` is used and defaults correctly to the `.env` file in the root directory.

The switch to `yarn` is OK, but I am not sure why NPM 8 works OK, but NPM 9 fails.

**Comment by aacebo** [comment]
This PR is getting pretty old, is it still needed and if so can we get it merged soon?

**Comment by corinagum** [comment]
Closing due to no activity.

**Pull request closed without merging**
