### PR TITLE
[C#] feat: Allow passing custom credentials factory to CloudAdapter

### PR DESCRIPTION
**Pull request by stepro**
## Linked issues

closes: #2130

## Details

Added an additional constructor to CloudAdapter that allows passing a custom credentials factory to CloudAdapter. This enables using an alternative credentials factory, like FederatedServiceClientCredentialsFactory, instead of it being hardcoded to the ConfigurationServiceClientCredentialFactory.

## Attestation Checklist

- [x] My code follows the style guidelines of this project
- [x] I have checked for/fixed spelling, linting, and other errors
- [x] I have commented my code for clarity
- [x] I have made corresponding changes to the documentation (updating the doc strings in the code is sufficient)
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by aacebo — APPROVED** [review]

**Comment by stepro** [comment]
@aacebo what else is needed to merge this PR? I'm not authorized to merge. Thanks!

**Comment by aacebo** [comment]
@singhk97 can you take a look and merge this if you approve?

**Comment by stepro** [comment]
> @singhk97 can you take a look and merge this if you approve?

@singhk97 gentle ping on this - this is something we need to complete our SFI work. Thanks!

**Review by singhk97 — APPROVED** [review]

**Comment by singhk97** [comment]
Thanks for your PR @stepro.

**Pull request merged**
