### PR TITLE
[C#] port: missing properties on ActionPlanner

### PR DESCRIPTION
**Pull request by nkrama-99**
## Linked issues

closes: #1274 

## Details
- port missing relevant public gets

### CODE REVIEW

**Comment by nkrama-99** [comment]
@microsoft-github-policy-service agree

**Comment by singhk97** [comment]
@nkrama-99  can you also add a public getting from `defaultPrompt`: https://github.com/microsoft/teams-ai/blob/09ebba139104816ea675e6e7958e479c7c3de6d2/js/packages/teams-ai/src/planners/ActionPlanner.ts#L127-L136

**Comment by nkrama-99** [comment]
@singhk97 defaultPrompt in js project is a "string?" which is only populated if this._options.defaultPrompt is also a string (the property defaultPrompt in ActionPlannerOptions is a "string | ActionPlannerPromptFactory"). In C# project, it can only be of one type, and it's ActionPlannerPromptFactory. If I were to add a public getter for defaultOptions, would it be of type ActionPlannerPromptFactory?

**Comment by singhk97** [comment]
The JS provides more flexibility (string or fn) in setting the default prompt since it supports union types. C# only supports passing in a delegate, which is restrictive but doesn't change the possible values that can be assigned the `DefaultPrompt`.

So yeah, the C# `DefaultPrompt` should be the `ActionPlannerPromptFactory` type. Thanks for clarifying @nkrama-99!

**Comment by nkrama-99** [comment]
@singhk97 thanks for the clarification! I've made the changes.

**Review by corinagum — APPROVED** [review]

**Review by singhk97 — APPROVED** [review]

**Comment by singhk97** [comment]
Thanks @nkrama-99!

**Pull request merged**
