### PR TITLE
[repo] fix: fix pngs due to LFS change

### PR DESCRIPTION
**Pull request by blackchoey**
## Linked issues

closes: #520

## Details

`git add --renormalize .` all the impacted files

#### Change details

> Describe your changes, with screenshots and code snippets as appropriate

**code snippets**:

**screenshots**:

## Attestation Checklist

- [ ] My code follows the style guidelines of this project

- I have checked for/fixed spelling, linting, and other errors
- I have commented my code for clarity
- I have made corresponding changes to the documentation (we use [TypeDoc](https://typedoc.org/) to document our code)
- My changes generate no new warnings
- I have added tests that validates my changes, and provides sufficient test coverage. I have tested with:
  - Local testing
  - E2E testing in Teams
- New and existing unit tests pass locally with my changes

### Additional information

> Feel free to add other relevant information below

### CODE REVIEW

**Review by aacebo — CHANGES_REQUESTED** [review]
this PR should be made against `main` for the C# and JS files first and then merged into the `python` branch to avoid mass conflicts.

**Comment by corinagum** [comment]
> this PR should be made against `main` for the C# and JS files first and then merged into the `python` branch to avoid mass conflicts.

Agreed on this. @blackchoey would you be able to do the PR or do you need support?

**Comment by corinagum** [comment]
@blackchoey I made a new PR: https://github.com/microsoft/teams-ai/pull/560 -- this doesn't include `PYTHON` branch

**Comment by blackchoey** [comment]
> @blackchoey I made a new PR: #560 -- this doesn't include `PYTHON` branch

Thanks for making that. I just didn't get time to update this PR. Will close this PR.

**Pull request closed without merging**
